export {
  DigitalCredentialsRequest,
  DigitalCredentialsCreateRequest,
  RegisterCreationOptionsOptions,
  RegisterCredentialsOptions,
  SendErrorResponseOptions,
  SendResponseOptions,
  SendCreateErrorResponseOptions,
  SendCreateResponseOptions,
  SetAllowedAppsOptions,
  AptitudeConsortiumConfig,
  AptitudeConsortiumCredentialConfig,
  AptitudeConsortiumFieldConfig,
  AptitudeConsortiumTransactionDataConfig,
  AptitudeConsortiumOpenId4VpConfig,
  AptitudeConsortiumOpenId4VciConfig,
  AptitudeConsortiumPlanOptions,
  AptitudeConsortiumLogLevel,
  ClaimsPathPointer,
} from './DigitalCredentialsApi.types'
export {
  registerCreationOptions,
  registerCredentials,
  sendErrorResponse,
  sendResponse,
  sendCreateErrorResponse,
  sendCreateResponse,
  setAllowedApps,
  isGetCredentialActivity,
  isCreateCredentialActivity,
} from './api'
